### ISSUE TITLE
Map doesn't appear when height is set with a percentage

### ISSUE THREAD

**Issue by kaiiorg** [Esri/angular-cli-esri-map#11]
I've implemented the example in my project using version 4.7 of the API. In my scss file, I can set the mapViewNode to ```height: 500px``` and the map appears, but obviously doesn't fill the screen if it taller than 500px. 

I tried setting it to ```height: 100%``` and the map never shows. There aren't any errors in the console and it appears to load all the scripts as it should, but never loads any tiles.

I'm not sure what I should do next in troubleshooting this, any suggestions?

map.component.ts:
```typescript
import { Component, OnInit, ElementRef, Input, Output, EventEmitter, ViewChild } from '@angular/core';
import { loadModules } from 'esri-loader';

import esri = __esri;

@Component({
  selector: 'app-map',
  templateUrl: './map.component.html',
  styleUrls: ['./map.component.scss']
})
export class MapComponent implements OnInit {

  // ESRI Loader options
  loaderOptions = {
    url: 'https://js.arcgis.com/4.7/'
  };

  // Default values
  private _zoom = 10;
  private _center = [-89.600223, 37.378633];
  private _basemap = 'streets';

  @Input()
  set zoom(zoom: number) {
    this._zoom = zoom;
  }
  get zoom(): number {
    return this._zoom;
  }

  @Input()
  set center(center: any[]) {
    this._center = center;
  }
  get center(): any[] {
    return this._center;
  }

  @Input()
  set basemap(basemap: string) {
    this._basemap = basemap;
  }
  get basemap(): string {
    return this._basemap;
  }

  @Output() mapLoaded = new EventEmitter<boolean>();

  @ViewChild('mapViewNode') private mapViewE1: ElementRef;

  constructor() { }

  ngOnInit() {
    loadModules([
      'esri/Map',
      'esri/views/MapView'
    ], this.loaderOptions)
    .then(([EsriMap, EsriMapView]) => {
      // Set type for Map constructor properties
      const mapProperties: esri.MapProperties = {
        basemap: this._basemap
      };

      const map: esri.Map = new EsriMap(mapProperties);

      // Set type for MapView constructor properties
      const mapViewProperties: esri.MapViewProperties = {
        container: this.mapViewE1.nativeElement,
        center: this._center,
        zoom: this._zoom,
        map: map
      };

      const mapView: esri.MapView = new EsriMapView(mapViewProperties);

      mapView.when(() => {
        // All the resources in the MapView have loaded. Now execute additional processes
        this.mapLoaded.emit(true);
      }, err => {
        console.error(err);
      });
    })
    .catch(err => {
      console.error(err);
    });
  }

}
```

map.component.html:
```html
<!--The div that the map gets injected into-->
<div #mapViewNode id="mapViewNode"></div>
```

map.component.scss (not working):
```scss
@import url('https://js.arcgis.com/4.7/esri/themes/dark/main.css');
#mapViewNode {
    height: 100%;
}
```

map.component.scss (working):
```scss
@import url('https://js.arcgis.com/4.7/esri/themes/dark/main.css');
#mapViewNode {
    height: 500px;
}
```

**Comment by andygup** [comment]
I'm able to reproduce this...for some reason `esri-view-surface` doesn't get populated. At the moment I don't know of a work-around, but I'll take a deeper look.

```html
<div class="esri-view-surface" style="user-select: none;"></div>
```

**Comment by andygup** [comment]
@kaiiorg try adding the following css to `app.component.css`:

```css
:host {
  position: absolute;
  left: 0;
  right: 0;
  bottom: 0;
  top: 0;
}
```

And, in `map.component.css`:

```css
.esri-view {
  height: 100%;
}
```

**Comment by vjamwec13579** [comment]
This is an issue for me as well

**Comment by vjamwec13579** [comment]
This should not be closed.

**Comment by andygup** [comment]
@vjamwec13579 fixed in https://github.com/Esri/angular-cli-esri-map/commit/0da9d6a86574c6cc5795c5cb11d70ad26c5a0048

Important note, the correct css uses a `:` and not a `.` reference => https://github.com/Esri/angular-cli-esri-map/issues/11#issuecomment-385449067

```css
:host {
  position: absolute;
  left: 0;
  right: 0;
  bottom: 0;
  top: 0;
}
```
